name: raymay
description: "Reimei Fujii Quick Order App"
publish_to: 'none'
version: 1.2.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.1
  flutter_barcode_scanner: ^2.0.0
  persistent_bottom_nav_bar: ^5.0.2
  button_navigation_bar: ^0.1.3
  dio: ^5.4.0
  shared_preferences: ^2.0.0
  http: ^1.2.0
  calendar_date_picker2: ^0.5.3
  image_picker: ^1.0.7
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.3
  open_file: ^3.3.2
  pdf: ^3.10.8
  universal_html: ^2.2.4
  uni_links: ^0.5.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Hira
      fonts:
        - asset: assets/fonts/hira.otf
